object Versions {
    const val gradlePlugin = "7.0.2"
    const val kotlin = "1.5.21"
    const val hiltAndroidGradlePlugin = "2.38.1"
    const val compose = "1.0.2"
    const val appCompat = "1.3.1"
    const val coreKtx = "1.3.1"
    const val material = "1.4.0"
    const val runtimeLivedata = "1.0.2"
    const val navigationCompose = "2.4.0-alpha08"
    const val activityCompose = "1.3.1"
    const val lifecycleKtx = "2.3.1"
    const val hiltAndroid = "2.38.1"
    const val converterGson = "2.9.0"
    const val kotlinxCoroutinesAndroid = "1.5.0"
    const val retrofitLoggingInterceptor = "4.9.0"
    const val jUnit = "4.+"
    const val mockk = "1.10.0"
    const val kluent = "1.14"
    const val robolectric = "4.4"
    const val testRules = "1.4.0"
    const val androidxJunit = "1.1.3"
    const val espressoCore = "3.4.0"
}